#!/bin/bash
set -e
export PG_APP_USER=$POSTGRES_DB_APP_USER;
export PG_APP_PASS=$POSTGRES_DB_APP_PASS;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER postgres SUPERUSER;
  ALTER DATABASE postgres OWNER TO postgres;
  CREATE USER $PG_APP_USER WITH PASSWORD '$PG_APP_PASS';
  ALTER USER $PG_APP_USER CREATEDB;
  ALTER DATABASE $POSTGRES_DB OWNER TO $PG_APP_USER;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $PG_APP_USER;

    \connect $POSTGRES_DB $PG_APP_USER
    BEGIN;

EOSQL

